# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Common/Common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aProtos/Common/Common.proto\x12\tCommonRpc\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/protobuf/any.proto\"i\n\x06Result\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12-\n\x07Message\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\"\n\x04\x44\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"E\n\x08SyncInfo\x12\x39\n\x13VendorServerAddress\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\x9c\x01\n\x0cNotification\x12+\n\x05Topic\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\nRoutingKey\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07Message\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"h\n\rInvokeRequest\x12*\n\x04Type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05Param\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"<\n\x0eInvokeResponse\x12*\n\x04\x44\x61ta\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"f\n\x0b\x44\x61taRequest\x12*\n\x04Type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x05Param\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"f\n\x0c\x44\x61taResponse\x12*\n\x04Type\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x04\x44\x61ta\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueB\x0f\xaa\x02\x0c\x43ommonRpc.V1b\x06proto3')



_RESULT = DESCRIPTOR.message_types_by_name['Result']
_SYNCINFO = DESCRIPTOR.message_types_by_name['SyncInfo']
_NOTIFICATION = DESCRIPTOR.message_types_by_name['Notification']
_INVOKEREQUEST = DESCRIPTOR.message_types_by_name['InvokeRequest']
_INVOKERESPONSE = DESCRIPTOR.message_types_by_name['InvokeResponse']
_DATAREQUEST = DESCRIPTOR.message_types_by_name['DataRequest']
_DATARESPONSE = DESCRIPTOR.message_types_by_name['DataResponse']
Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.Result)
  })
_sym_db.RegisterMessage(Result)

SyncInfo = _reflection.GeneratedProtocolMessageType('SyncInfo', (_message.Message,), {
  'DESCRIPTOR' : _SYNCINFO,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.SyncInfo)
  })
_sym_db.RegisterMessage(SyncInfo)

Notification = _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATION,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.Notification)
  })
_sym_db.RegisterMessage(Notification)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), {
  'DESCRIPTOR' : _INVOKEREQUEST,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.InvokeRequest)
  })
_sym_db.RegisterMessage(InvokeRequest)

InvokeResponse = _reflection.GeneratedProtocolMessageType('InvokeResponse', (_message.Message,), {
  'DESCRIPTOR' : _INVOKERESPONSE,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.InvokeResponse)
  })
_sym_db.RegisterMessage(InvokeResponse)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

DataResponse = _reflection.GeneratedProtocolMessageType('DataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DATARESPONSE,
  '__module__' : 'Protos.Common.Common_pb2'
  # @@protoc_insertion_point(class_scope:CommonRpc.DataResponse)
  })
_sym_db.RegisterMessage(DataResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\014CommonRpc.V1'
  _RESULT._serialized_start=100
  _RESULT._serialized_end=205
  _SYNCINFO._serialized_start=207
  _SYNCINFO._serialized_end=276
  _NOTIFICATION._serialized_start=279
  _NOTIFICATION._serialized_end=435
  _INVOKEREQUEST._serialized_start=437
  _INVOKEREQUEST._serialized_end=541
  _INVOKERESPONSE._serialized_start=543
  _INVOKERESPONSE._serialized_end=603
  _DATAREQUEST._serialized_start=605
  _DATAREQUEST._serialized_end=707
  _DATARESPONSE._serialized_start=709
  _DATARESPONSE._serialized_end=811
# @@protoc_insertion_point(module_scope)
