# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Protos/Processor/ProcessorHealth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from Protos.Common import Common_pb2 as Protos_dot_Common_dot_Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&Protos/Processor/ProcessorHealth.proto\x12\x12ProcessorHealthRpc\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1aProtos/Common/Common.proto\"\x1d\n\x1bProcessorHealthCheckRequest\"K\n\x0fProcessorStatus\x12(\n\x02Id\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0e\n\x06Status\x18\x02 \x01(\x05\"V\n\x1cProcessorHealthCheckResponse\x12\x36\n\tProcessor\x18\x01 \x01(\x0b\x32#.ProcessorHealthRpc.ProcessorStatus2k\n\x16ProcessorHealthService\x12Q\n\x0bHealthCheck\x12/.ProcessorHealthRpc.ProcessorHealthCheckRequest\x1a\x11.CommonRpc.ResultB\x18\xaa\x02\x15ProcessorHealthRpc.V1b\x06proto3')



_PROCESSORHEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['ProcessorHealthCheckRequest']
_PROCESSORSTATUS = DESCRIPTOR.message_types_by_name['ProcessorStatus']
_PROCESSORHEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['ProcessorHealthCheckResponse']
ProcessorHealthCheckRequest = _reflection.GeneratedProtocolMessageType('ProcessorHealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSORHEALTHCHECKREQUEST,
  '__module__' : 'Protos.Processor.ProcessorHealth_pb2'
  # @@protoc_insertion_point(class_scope:ProcessorHealthRpc.ProcessorHealthCheckRequest)
  })
_sym_db.RegisterMessage(ProcessorHealthCheckRequest)

ProcessorStatus = _reflection.GeneratedProtocolMessageType('ProcessorStatus', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSORSTATUS,
  '__module__' : 'Protos.Processor.ProcessorHealth_pb2'
  # @@protoc_insertion_point(class_scope:ProcessorHealthRpc.ProcessorStatus)
  })
_sym_db.RegisterMessage(ProcessorStatus)

ProcessorHealthCheckResponse = _reflection.GeneratedProtocolMessageType('ProcessorHealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSORHEALTHCHECKRESPONSE,
  '__module__' : 'Protos.Processor.ProcessorHealth_pb2'
  # @@protoc_insertion_point(class_scope:ProcessorHealthRpc.ProcessorHealthCheckResponse)
  })
_sym_db.RegisterMessage(ProcessorHealthCheckResponse)

_PROCESSORHEALTHSERVICE = DESCRIPTOR.services_by_name['ProcessorHealthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\025ProcessorHealthRpc.V1'
  _PROCESSORHEALTHCHECKREQUEST._serialized_start=122
  _PROCESSORHEALTHCHECKREQUEST._serialized_end=151
  _PROCESSORSTATUS._serialized_start=153
  _PROCESSORSTATUS._serialized_end=228
  _PROCESSORHEALTHCHECKRESPONSE._serialized_start=230
  _PROCESSORHEALTHCHECKRESPONSE._serialized_end=316
  _PROCESSORHEALTHSERVICE._serialized_start=318
  _PROCESSORHEALTHSERVICE._serialized_end=425
# @@protoc_insertion_point(module_scope)
