# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos.Common import Common_pb2 as Protos_dot_Common_dot_Common__pb2


class ProcessorRuntimeServiceStub(object):
    """大核通用应用服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notify = channel.unary_unary(
                '/ProcessorRuntimeRpc.ProcessorRuntimeService/Notify',
                request_serializer=Protos_dot_Common_dot_Common__pb2.Notification.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_Common__pb2.Result.FromString,
                )


class ProcessorRuntimeServiceServicer(object):
    """大核通用应用服务
    """

    def Notify(self, request, context):
        """通知
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessorRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=Protos_dot_Common_dot_Common__pb2.Notification.FromString,
                    response_serializer=Protos_dot_Common_dot_Common__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProcessorRuntimeRpc.ProcessorRuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessorRuntimeService(object):
    """大核通用应用服务
    """

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessorRuntimeRpc.ProcessorRuntimeService/Notify',
            Protos_dot_Common_dot_Common__pb2.Notification.SerializeToString,
            Protos_dot_Common_dot_Common__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
