# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Protos.Common import Common_pb2 as Protos_dot_Common_dot_Common__pb2
from Protos.Processor import ProcessorHealth_pb2 as Protos_dot_Processor_dot_ProcessorHealth__pb2


class ProcessorHealthServiceStub(object):
    """大核健康检查
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ProcessorHealthRpc.ProcessorHealthService/HealthCheck',
                request_serializer=Protos_dot_Processor_dot_ProcessorHealth__pb2.ProcessorHealthCheckRequest.SerializeToString,
                response_deserializer=Protos_dot_Common_dot_Common__pb2.Result.FromString,
                )


class ProcessorHealthServiceServicer(object):
    """大核健康检查
    """

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessorHealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=Protos_dot_Processor_dot_ProcessorHealth__pb2.ProcessorHealthCheckRequest.FromString,
                    response_serializer=Protos_dot_Common_dot_Common__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProcessorHealthRpc.ProcessorHealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessorHealthService(object):
    """大核健康检查
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProcessorHealthRpc.ProcessorHealthService/HealthCheck',
            Protos_dot_Processor_dot_ProcessorHealth__pb2.ProcessorHealthCheckRequest.SerializeToString,
            Protos_dot_Common_dot_Common__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
